version: '3.8'

services:
  db:
    image: postgres:16.9
    restart: on-failure
    environment:
      POSTGRES_DB: eatery
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: wasd1234
    ports:
      - "5432:5432"
    volumes:
      - eat:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  eat:
  redis-data:
